### ISSUE TITLE
Documentar periodo de actualización del mapa y fuentes

### ISSUE THREAD

**Issue by calderonsamuel** [musajajorge/mapsPERU#1]
Hola, gracias por poner estos mapas a disposición. Agradecería puedas incluir información acerca de la fuente de las geometrías y el perido de actualización. Estos datos son importantes cuando se requiere cruzar con información proveniente de otras fuentes. Gracias!

**Comment by musajajorge** [comment]
Hola, la información la puedes encontrar aquí: https://zenodo.org/record/5758269

Si bien no hay nuevos distritos creados en los últimos años, entiendo que sí es factible que por motivos políticos los límites puedan ajustarse un poco. Espero actualizar a principios del 2023 los mapas.

Saludos.
